all_countries = {
             'AF': 'Afghanistan',
             'AL': 'Albania',
             'DZ': 'Algeria',
             'AO': 'Angola',
             'AR': 'Argentina',
             'AM': 'Armenia',
             'AU': 'Australia',
             'AT': 'Austria',
             'AZ': 'Azerbaijan',
             'BH': 'Bahrain',
             'BD': 'Bangladesh',
             'BY': 'Belarus',
             'BE': 'Belgium',
             'BJ': 'Benin',
             'BO': 'Bolivia',
             'BA': 'Bosnia and Herzegovina',
             'BW': 'Botswana',
             'BR': 'Brazil',
             'BG': 'Bulgaria',
             'BF': 'Burkina Faso',
             'BI': 'Burundi',
             'KH': 'Cambodia',
             'CM': 'Cameroon',
             'CA': 'Canada',
             'CF': 'Central African Republic',
             'TD': 'Chad',
             'CL': 'Chile',
             'CO': 'Colombia',
             'CD': 'Congo',
             'CR': 'Costa Rica',
             'CI': 'Côte',
             'HR': 'Croatia',
             'CU': 'Cuba',
             'CY': 'Cyprus',
             'CZ': 'Czech Republic',
             'DK': 'Denmark',
             'DJ': 'Djibouti',
             'DO': 'Dominican Republic',
             'EC': 'Ecuador',
             'EG': 'Egypt',
             'SV': 'El Salvador',
             'GQ': 'Equatorial Guinea',
             'EE': 'Estonia',
             'ET': 'Ethiopia',
             'FI': 'Finland',
             'FR': 'France',
             'GA': 'Gabon',
             'GM': 'Gambia',
             'GE': 'Georgia',
             'DE': 'Germany',
             'GH': 'Ghana',
             'GR': 'Greece',
             'GT': 'Guatemala',
             'GN': 'Guinea',
             'HN': 'Honduras',
             'HK': 'Hong Kong',
             'HU': 'Hungary',
             'IS': 'Iceland',
             'IN': 'India',
             'ID': 'Indonesia',
             'IR': 'Iran',
             'IQ': 'Iraq',
             'IE': 'Ireland',
             'IL': 'Israel',
             'IT': 'Italy',
             'JM': 'Jamaica',
             'JP': 'Japan',
             'JO': 'Jordan',
             'KZ': 'Kazakhstan',
             'KE': 'Kenya',
             'KW': 'Kuwait',
             'LA': 'Laos',
             'LV': 'Latvia',
             'LB': 'Lebanon',
             'LR': 'Liberia',
             'LY': 'Libya',
             'LT': 'Lithuania',
             'LU': 'Luxembourg',
             'MK': 'Macedonia',
             'MG': 'Madagascar',
             'MW': 'Malawi',
             'MY': 'Malaysia',
             'ML': 'Mali',
             'MT': 'Malta',
             'MR': 'Mauritania',
             'MX': 'Mexico',
             'MD': 'Moldova',
             'MN': 'Mongolia',
             'ME': 'Montenegro',
             'MA': 'Morocco',
             'MZ': 'Mozambique',
             'MM': 'Myanmar',
             'NA': 'Namibia',
             'NP': 'Nepal',
             'NL': 'Netherlands',
             'NZ': 'New Zealand',
             'NI': 'Nicaragua',
             'NE': 'Niger',
             'NG': 'Nigeria',
             'MK': 'North Macedonia',
             'NO': 'Norway',
             'OM': 'Oman',
             'PK': 'Pakistan',
             'PS': 'Palestine',
             'PA': 'Panama',
             'PY': 'Paraguay',
             'PE': 'Peru',
             'PH': 'Philippines',
             'PL': 'Poland',
             'PT': 'Portugal',
             'PR': 'Puerto Rico',
             'QA': 'Qatar',
             'RO': 'Romania',
             'RU': 'Russia',
             'RW': 'Rwanda',
             'SA': 'Saudi Arabia',
             'SN': 'Senegal',
             'RS': 'Serbia',
             'SL': 'Sierra Leone',
             'SG': 'Singapore',
             'SK': 'Slovakia',
             'SI': 'Slovenia',
             'SO': 'Somalia',
             'ZA': 'South Africa',
             'KR': 'South Korea',
             'SS': 'South Sudan',
             'ES': 'Spain',
             'LK': 'Sri Lanka',
             'SD': 'Sudan',
             'SE': 'Sweden',
             'CH': 'Switzerland',
             'SY': 'Syrian Arab Republic',
             'TW': 'Taiwan',
             'TZ': 'Tanzania',
             'TH': 'Thailand',
             'TG': 'Togo',
             'TN': 'Tunisia',
             'TR': 'Turkey',
             'TM': 'Turkmenistan',
             'UG': 'Uganda',
             'UA': 'Ukraine',
             'AE': 'United Arab Emirates',
             'GB': 'United Kingdom',
             'US': 'United States',
             'UY': 'Uruguay',
             'UZ': 'Uzbekistan',
             'VE': 'Venezuela',
             'VN': 'Vietnam',
             'YE': 'Yemen',
             'ZM': 'Zambia',
             'ZW': 'Zimbabwe',
            }